<a href="https://colab.research.google.com/github/JMCVALE/ASN-ROCKS-/blob/main/RedesNeurais_hiperparametros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**1) Iris Dataset (3 classes de target, 150 amostras)**
Classificação — (3 classes de target, 150 amostras)

### **Exercício 1a** - Ajuste um modelo de redes neurais MLP para resolução do problema do Íris (classificação de amostras entre 3 possíveis categorias), determine a quantidade de camadas ocultas e neurônios, bem como a função de ativação da(s) camada(s) oculta(s) (sugestão: teste diferentes valores para encontrar o de melhor desempenho). Configure para utilizar early stopping e defina 500 iterações máximas.

hidden_layer_sizes : Define a arquitetura da rede neural, ou seja, quantos neurônios e camadas ocultas ela terá.

activation: Define a função de ativação usada nas camadas ocultas.

early_stopping: Controla se o treinamento deve parar automaticamente quando o desempenho em validação não melhora.

solver: Define o otimizador usado para ajustar os pesos da rede neural.

max_iter: Define o número máximo de iterações (épocas) para o treinamento.

random_state: Controla a aleatoriedade dos pesos iniciais e do embaralhamento dos dados.

In [ ]:
# Inicialização
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
# Carregar base
X, y = load_iris(return_X_y=True)
iris = load_iris()

# Converter para DataFrame
df = pd.DataFrame(X, columns=iris.feature_names)
df["target"] = y

# Ver primeiras linhas
print(df.head())

# Resumo
print(iris.DESCR)  # descrição detalhada da base
print(df.info())   # resumo das colunas e tipos
print(df['target'].value_counts())  # quantas amostras em cada classe

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

   target
0       0
1       0
2       0
3       0
4       0
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB
None
target
0    50
1    50
2    50
Name: count, dtype: int64

Dividir a base em treino e teste.

In [ ]:
X, y = load_iris(return_X_y=True)
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

Padronizar as variáveis porque estão em escalas bem diferentes

In [ ]:
scaler = StandardScaler()
X_tr_s = scaler.fit_transform(X_tr)
X_te_s = scaler.transform(X_te)

Configurar os hiperparâmetros da rede neural

In [ ]:
# Configure os parâmetros corretamente

clf = MLPClassifier(hidden_layer_sizes = (64, 2),
                    activation = 'relu',
                    early_stopping = True,
                    solver = 'sgd',
                    max_iter = 500,
                    random_state=42)
clf.fit(X_tr_s, y_tr)

y_pred = clf.predict(X_te_s)
print("Acurácia:", f"{accuracy_score(y_te, y_pred):.2%}")
print(classification_report(y_te, y_pred, digits=3))

Acurácia: 60.00%
              precision    recall  f1-score   support

           0      0.833     1.000     0.909        10
           1      0.444     0.800     0.571        10
           2      0.000     0.000     0.000        10

    accuracy                          0.600        30
   macro avg      0.426     0.600     0.494        30
weighted avg      0.426     0.600     0.494        30

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Testando diferentes configurações de hiperparâmetros e early stopping

In [ ]:
# Configurações para testar
configs = [
    {"hidden_layer_sizes": (64, 2), "activation": "relu", "solver": "sgd"},
    {"hidden_layer_sizes": (8,4), "activation": "tanh", "solver": "sgd"},
    {"hidden_layer_sizes": (2,1), "activation": "tanh", "solver": "sgd"},
    {"hidden_layer_sizes": (15,2), "activation": "logistic", "solver": "sgd"},
    {"hidden_layer_sizes": (20, 5), "activation": "relu", "solver": "sgd"},
]

# Rodar os testes
results = []
for i, cfg in enumerate(configs, 1):
    clf = MLPClassifier(
        hidden_layer_sizes=cfg["hidden_layer_sizes"],
        activation=cfg["activation"],
        solver=cfg["solver"],
        early_stopping=True,
        max_iter=500,
        random_state=42
    )

    clf.fit(X_tr_s, y_tr)
    y_pred = clf.predict(X_te_s)
    acc = accuracy_score(y_te, y_pred)

    results.append({
        "Teste": i,
        "Camadas Ocultas": cfg["hidden_layer_sizes"],
        "Ativação": cfg["activation"],
        "Solver": cfg["solver"],
        "Acurácia": round(acc * 100, 2)
    })

    print(f"=== Teste {i} ===")
    print(f"Configuração: {cfg}")
    print(f"Acurácia: {acc*100:.2f}%")
    print(classification_report(y_te, y_pred, digits=2))
    print("-"*50)

# 5️⃣ Mostrar resumo dos resultados
df_results = pd.DataFrame(results)
print("\nResumo dos testes:")
display(df_results)

=== Teste 1 ===
Configuração: {'hidden_layer_sizes': (64, 2), 'activation': 'relu', 'solver': 'sgd'}
Acurácia: 60.00%
              precision    recall  f1-score   support

           0       0.83      1.00      0.91        10
           1       0.44      0.80      0.57        10
           2       0.00      0.00      0.00        10

    accuracy                           0.60        30
   macro avg       0.43      0.60      0.49        30
weighted avg       0.43      0.60      0.49        30

--------------------------------------------------
=== Teste 2 ===
Configuração: {'hidden_layer_sizes': (8, 4), 'activation': 'tanh', 'solver': 'sgd'}
Acurácia: 53.33%
              precision    recall  f1-score   support

           0       0.80      0.80      0.80        10
           1       0.40      0.80      0.53        10
           2       0.00      0.00      0.00        10

    accuracy                           0.53        30
   macro avg       0.40      0.53      0.44        30
weighted avg       0.40      0.53      0.44        30

--------------------------------------------------
=== Teste 3 ===
Configuração: {'hidden_layer_sizes': (2, 1), 'activation': 'tanh', 'solver': 'sgd'}
Acurácia: 33.33%
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.33      1.00      0.50        10
           2       0.00      0.00      0.00        10

    accuracy                           0.33        30
   macro avg       0.11      0.33      0.17        30
weighted avg       0.11      0.33      0.17        30

--------------------------------------------------
=== Teste 4 ===
Configuração: {'hidden_layer_sizes': (15, 2), 'activation': 'logistic', 'solver': 'sgd'}
Acurácia: 33.33%
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.00      0.00      0.00        10
           2       0.33      1.00      0.50        10

    accuracy                           0.33        30
   macro avg       0.11      0.33      0.17        30
weighted avg       0.11      0.33      0.17        30

--------------------------------------------------
=== Teste 5 ===
Configuração: {'hidden_layer_sizes': (20, 5), 'activation': 'relu', 'solver': 'sgd'}
Acurácia: 33.33%
              precision    recall  f1-score   support

           0       0.33      1.00      0.50        10
           1       0.00      0.00      0.00        10
           2       0.00      0.00      0.00        10

    accuracy                           0.33        30
   macro avg       0.11      0.33      0.17        30
weighted avg       0.11      0.33      0.17        30

--------------------------------------------------

Resumo dos testes:

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

   Teste Camadas Ocultas  Ativação Solver  Acurácia
0      1         (64, 2)      relu    sgd     60.00
1      2          (8, 4)      tanh    sgd     53.33
2      3          (2, 1)      tanh    sgd     33.33
3      4         (15, 2)  logistic    sgd     33.33
4      5         (20, 5)      relu    sgd     33.33

Seguindo o enunciado do Exercício 1a, foi ajustado um modelo de rede neural MLP para o problema de classificação do conjunto de dados Iris, testando diferentes combinações de camadas ocultas, neurônios e funções de ativação. Todas as configurações utilizaram o otimizador sgd (Stochastic Gradient Descent), limite de 500 iterações e o parâmetro early_stopping=True, conforme solicitado. Foram avaliadas cinco arquiteturas distintas, variando entre as funções de ativação relu, tanh e logistic.

Os resultados mostraram acurácias entre 33,33% e 60%, indicando que, com o early stopping ativado, o modelo interrompeu o treinamento antes de atingir o melhor ponto de aprendizado. A melhor configuração foi (64, 2) com função relu, atingindo 60% de acurácia. Esse comportamento demonstra que o uso do early_stopping, embora útil para evitar overfitting, pode causar underfitting em bases pequenas como a Iris, pois o treinamento é interrompido precocemente. Dessa forma, os testes evidenciam como a quantidade de camadas, a função de ativação e o controle de parada influenciam diretamente o desempenho do modelo na classificação multiclasse.

In [ ]:
ativacoes = ['identity', 'logistic', 'tanh', 'relu']

for a in ativacoes:
    clf = MLPClassifier(hidden_layer_sizes=(10,10),
                        activation=a,
                        solver='sgd',
                        early_stopping=False,
                        max_iter=800,
                        random_state=42)
    clf.fit(X_tr_s, y_tr)
    y_pred = clf.predict(X_te_s)
    acc = accuracy_score(y_te, y_pred)
    print(f"Ativação: {a} → Acurácia: {acc*100:.2f}%")

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (800) reached and the optimization hasn't converged yet.
  warnings.warn(

Ativação: identity → Acurácia: 96.67%
Ativação: logistic → Acurácia: 33.33%

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (800) reached and the optimization hasn't converged yet.
  warnings.warn(

Ativação: tanh → Acurácia: 93.33%
Ativação: relu → Acurácia: 93.33%

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (800) reached and the optimization hasn't converged yet.
  warnings.warn(

Testando diferentes configurações de hiperparâmetros sem early stopping

In [ ]:
# Configurações para testar
configs = [
    {"hidden_layer_sizes": (64, 2), "activation": "relu", "solver": "sgd"},
    {"hidden_layer_sizes": (8,4), "activation": "tanh", "solver": "sgd"},
    {"hidden_layer_sizes": (2,1), "activation": "tanh", "solver": "sgd"},
    {"hidden_layer_sizes": (15,2), "activation": "logistic", "solver": "sgd"},
    {"hidden_layer_sizes": (20, 5), "activation": "tanh", "solver": "sgd"},
]

# Rodar os testes
results = []
for i, cfg in enumerate(configs, 1):
    clf = MLPClassifier(
        hidden_layer_sizes=cfg["hidden_layer_sizes"],
        activation=cfg["activation"],
        solver=cfg["solver"],
        early_stopping=False,
        max_iter=500,
        random_state=42
    )

    clf.fit(X_tr_s, y_tr)
    y_pred = clf.predict(X_te_s)
    acc = accuracy_score(y_te, y_pred)

    results.append({
        "Teste": i,
        "Camadas Ocultas": cfg["hidden_layer_sizes"],
        "Ativação": cfg["activation"],
        "Solver": cfg["solver"],
        "Acurácia": round(acc * 100, 2)
    })

    print(f"=== Teste {i} ===")
    print(f"Configuração: {cfg}")
    print(f"Acurácia: {acc*100:.2f}%")
    print(classification_report(y_te, y_pred, digits=2))
    print("-"*50)

# Mostrar resumo dos resultados
df_results = pd.DataFrame(results)
print("\nResumo dos testes:")
display(df_results)

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

=== Teste 1 ===
Configuração: {'hidden_layer_sizes': (64, 2), 'activation': 'relu', 'solver': 'sgd'}
Acurácia: 66.67%
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.50      1.00      0.67        10
           2       0.00      0.00      0.00        10

    accuracy                           0.67        30
   macro avg       0.50      0.67      0.56        30
weighted avg       0.50      0.67      0.56        30

--------------------------------------------------

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

=== Teste 2 ===
Configuração: {'hidden_layer_sizes': (8, 4), 'activation': 'tanh', 'solver': 'sgd'}
Acurácia: 70.00%
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.56      0.50      0.53        10
           2       0.55      0.60      0.57        10

    accuracy                           0.70        30
   macro avg       0.70      0.70      0.70        30
weighted avg       0.70      0.70      0.70        30

--------------------------------------------------

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

=== Teste 3 ===
Configuração: {'hidden_layer_sizes': (2, 1), 'activation': 'tanh', 'solver': 'sgd'}
Acurácia: 70.00%
              precision    recall  f1-score   support

           0       0.91      1.00      0.95        10
           1       1.00      0.10      0.18        10
           2       0.56      1.00      0.71        10

    accuracy                           0.70        30
   macro avg       0.82      0.70      0.62        30
weighted avg       0.82      0.70      0.62        30

--------------------------------------------------
=== Teste 4 ===
Configuração: {'hidden_layer_sizes': (15, 2), 'activation': 'logistic', 'solver': 'sgd'}
Acurácia: 33.33%
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.00      0.00      0.00        10
           2       0.33      1.00      0.50        10

    accuracy                           0.33        30
   macro avg       0.11      0.33      0.17        30
weighted avg       0.11      0.33      0.17        30

--------------------------------------------------
=== Teste 5 ===
Configuração: {'hidden_layer_sizes': (20, 5), 'activation': 'tanh', 'solver': 'sgd'}
Acurácia: 90.00%
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.70      0.82        10
           2       0.77      1.00      0.87        10

    accuracy                           0.90        30
   macro avg       0.92      0.90      0.90        30
weighted avg       0.92      0.90      0.90        30

--------------------------------------------------

Resumo dos testes:

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

   Teste Camadas Ocultas  Ativação Solver  Acurácia
0      1         (64, 2)      relu    sgd     66.67
1      2          (8, 4)      tanh    sgd     70.00
2      3          (2, 1)      tanh    sgd     70.00
3      4         (15, 2)  logistic    sgd     33.33
4      5         (20, 5)      tanh    sgd     90.00

Segui o exercício ajustando um MLP para o Iris e comparei cinco arquiteturas variando camadas e ativações, mantendo solver='sgd' e max_iter=500. Ao retirar o early stopping (early_stopping=False), o modelo pôde treinar até o limite de iterações usando 100% do conjunto de treino, o que reduziu underfitting e elevou a acurácia. A melhor configuração foi hidden_layer_sizes=(20, 5), activation='tanh', alcançando 90%. As ativações tanh tiveram desempenho superior às alternativas, enquanto logistic permaneceu fraca (33,33%).

### **Exercício 1b** - De acordo com o tipo de target, qual a função de custo utilizada?

O target do problema Iris é categórico multiclasse, pois representa três classes distintas de flores (setosa, versicolor e virginica). Para esse tipo de problema de classificação, o MLPClassifier utiliza como função de custo a entropia cruzada (cross-entropy loss), também chamada de log loss.

Essa função mede a diferença entre as probabilidades previstas pelo modelo e os valores reais das classes, penalizando previsões erradas com maior intensidade. Ela é ideal para tarefas de classificação porque ajusta o modelo de forma a maximizar a probabilidade da classe correta. Em resumo, o MLP tenta minimizar a cross-entropy loss para melhorar a precisão na predição das categorias.

In [ ]:
help(MLPClassifier)

Help on class MLPClassifier in module sklearn.neural_network._multilayer_perceptron:

class MLPClassifier(sklearn.base.ClassifierMixin, BaseMultilayerPerceptron)
 |  MLPClassifier(hidden_layer_sizes=(100,), activation='relu', *, solver='adam', alpha=0.0001, batch_size='auto', learning_rate='constant', learning_rate_init=0.001, power_t=0.5, max_iter=200, shuffle=True, random_state=None, tol=0.0001, verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True, early_stopping=False, validation_fraction=0.1, beta_1=0.9, beta_2=0.999, epsilon=1e-08, n_iter_no_change=10, max_fun=15000)
 |
 |  Multi-layer Perceptron classifier.
 |
 |  This model optimizes the log-loss function using LBFGS or stochastic
 |  gradient descent.
 |
 |  .. versionadded:: 0.18
 |
 |  Parameters
 |  ----------
 |  hidden_layer_sizes : array-like of shape(n_layers - 2,), default=(100,)
 |      The ith element represents the number of neurons in the ith
 |      hidden layer.
 |
 |  activation : {'identity', 'logistic', 'tanh', 'relu'}, default='relu'
 |      Activation function for the hidden layer.
 |
 |      - 'identity', no-op activation, useful to implement linear bottleneck,
 |        returns f(x) = x
 |
 |      - 'logistic', the logistic sigmoid function,
 |        returns f(x) = 1 / (1 + exp(-x)).
 |
 |      - 'tanh', the hyperbolic tan function,
 |        returns f(x) = tanh(x).
 |
 |      - 'relu', the rectified linear unit function,
 |        returns f(x) = max(0, x)
 |
 |  solver : {'lbfgs', 'sgd', 'adam'}, default='adam'
 |      The solver for weight optimization.
 |
 |      - 'lbfgs' is an optimizer in the family of quasi-Newton methods.
 |
 |      - 'sgd' refers to stochastic gradient descent.
 |
 |      - 'adam' refers to a stochastic gradient-based optimizer proposed
 |        by Kingma, Diederik, and Jimmy Ba
 |
 |      For a comparison between Adam optimizer and SGD, see
 |      :ref:`sphx_glr_auto_examples_neural_networks_plot_mlp_training_curves.py`.
 |
 |      Note: The default solver 'adam' works pretty well on relatively
 |      large datasets (with thousands of training samples or more) in terms of
 |      both training time and validation score.
 |      For small datasets, however, 'lbfgs' can converge faster and perform
 |      better.
 |
 |  alpha : float, default=0.0001
 |      Strength of the L2 regularization term. The L2 regularization term
 |      is divided by the sample size when added to the loss.
 |
 |      For an example usage and visualization of varying regularization, see
 |      :ref:`sphx_glr_auto_examples_neural_networks_plot_mlp_alpha.py`.
 |
 |  batch_size : int, default='auto'
 |      Size of minibatches for stochastic optimizers.
 |      If the solver is 'lbfgs', the classifier will not use minibatch.
 |      When set to "auto", `batch_size=min(200, n_samples)`.
 |
 |  learning_rate : {'constant', 'invscaling', 'adaptive'}, default='constant'
 |      Learning rate schedule for weight updates.
 |
 |      - 'constant' is a constant learning rate given by
 |        'learning_rate_init'.
 |
 |      - 'invscaling' gradually decreases the learning rate at each
 |        time step 't' using an inverse scaling exponent of 'power_t'.
 |        effective_learning_rate = learning_rate_init / pow(t, power_t)
 |
 |      - 'adaptive' keeps the learning rate constant to
 |        'learning_rate_init' as long as training loss keeps decreasing.
 |        Each time two consecutive epochs fail to decrease training loss by at
 |        least tol, or fail to increase validation score by at least tol if
 |        'early_stopping' is on, the current learning rate is divided by 5.
 |
 |      Only used when ``solver='sgd'``.
 |
 |  learning_rate_init : float, default=0.001
 |      The initial learning rate used. It controls the step-size
 |      in updating the weights. Only used when solver='sgd' or 'adam'.
 |
 |  power_t : float, default=0.5
 |      The exponent for inverse scaling learning rate.
 |      It is used in updating effective learning rate when the learning_rate
 |      is set to 'invscaling'. Only used when solver='sgd'.
 |
 |  max_iter : int, default=200
 |      Maximum number of iterations. The solver iterates until convergence
 |      (determined by 'tol') or this number of iterations. For stochastic
 |      solvers ('sgd', 'adam'), note that this determines the number of epochs
 |      (how many times each data point will be used), not the number of
 |      gradient steps.
 |
 |  shuffle : bool, default=True
 |      Whether to shuffle samples in each iteration. Only used when
 |      solver='sgd' or 'adam'.
 |
 |  random_state : int, RandomState instance, default=None
 |      Determines random number generation for weights and bias
 |      initialization, train-test split if early stopping is used, and batch
 |      sampling when solver='sgd' or 'adam'.
 |      Pass an int for reproducible results across multiple function calls.
 |      See :term:`Glossary <random_state>`.
 |
 |  tol : float, default=1e-4
 |      Tolerance for the optimization. When the loss or score is not improving
 |      by at least ``tol`` for ``n_iter_no_change`` consecutive iterations,
 |      unless ``learning_rate`` is set to 'adaptive', convergence is
 |      considered to be reached and training stops.
 |
 |  verbose : bool, default=False
 |      Whether to print progress messages to stdout.
 |
 |  warm_start : bool, default=False
 |      When set to True, reuse the solution of the previous
 |      call to fit as initialization, otherwise, just erase the
 |      previous solution. See :term:`the Glossary <warm_start>`.
 |
 |  momentum : float, default=0.9
 |      Momentum for gradient descent update. Should be between 0 and 1. Only
 |      used when solver='sgd'.
 |
 |  nesterovs_momentum : bool, default=True
 |      Whether to use Nesterov's momentum. Only used when solver='sgd' and
 |      momentum > 0.
 |
 |  early_stopping : bool, default=False
 |      Whether to use early stopping to terminate training when validation
 |      score is not improving. If set to true, it will automatically set
 |      aside 10% of training data as validation and terminate training when
 |      validation score is not improving by at least ``tol`` for
 |      ``n_iter_no_change`` consecutive epochs. The split is stratified,
 |      except in a multilabel setting.
 |      If early stopping is False, then the training stops when the training
 |      loss does not improve by more than tol for n_iter_no_change consecutive
 |      passes over the training set.
 |      Only effective when solver='sgd' or 'adam'.
 |
 |  validation_fraction : float, default=0.1
 |      The proportion of training data to set aside as validation set for
 |      early stopping. Must be between 0 and 1.
 |      Only used if early_stopping is True.
 |
 |  beta_1 : float, default=0.9
 |      Exponential decay rate for estimates of first moment vector in adam,
 |      should be in [0, 1). Only used when solver='adam'.
 |
 |  beta_2 : float, default=0.999
 |      Exponential decay rate for estimates of second moment vector in adam,
 |      should be in [0, 1). Only used when solver='adam'.
 |
 |  epsilon : float, default=1e-8
 |      Value for numerical stability in adam. Only used when solver='adam'.
 |
 |  n_iter_no_change : int, default=10
 |      Maximum number of epochs to not meet ``tol`` improvement.
 |      Only effective when solver='sgd' or 'adam'.
 |
 |      .. versionadded:: 0.20
 |
 |  max_fun : int, default=15000
 |      Only used when solver='lbfgs'. Maximum number of loss function calls.
 |      The solver iterates until convergence (determined by 'tol'), number
 |      of iterations reaches max_iter, or this number of loss function calls.
 |      Note that number of loss function calls will be greater than or equal
 |      to the number of iterations for the `MLPClassifier`.
 |
 |      .. versionadded:: 0.22
 |
 |  Attributes
 |  ----------
 |  classes_ : ndarray or list of ndarray of shape (n_classes,)
 |      Class labels for each output.
 |
 |  loss_ : float
 |      The current loss computed with the loss function.
 |
 |  best_loss_ : float or None
 |      The minimum loss reached by the solver throughout fitting.
 |      If `early_stopping=True`, this attribute is set to `None`. Refer to
 |      the `best_validation_score_` fitted attribute instead.
 |
 |  loss_curve_ : list of shape (`n_iter_`,)
 |      The ith element in the list represents the loss at the ith iteration.
 |
 |  validation_scores_ : list of shape (`n_iter_`,) or None
 |      The score at each iteration on a held-out validation set. The score
 |      reported is the accuracy score. Only available if `early_stopping=True`,
 |      otherwise the attribute is set to `None`.
 |
 |  best_validation_score_ : float or None
 |      The best validation score (i.e. accuracy score) that triggered the
 |      early stopping. Only available if `early_stopping=True`, otherwise the
 |      attribute is set to `None`.
 |
 |  t_ : int
 |      The number of training samples seen by the solver during fitting.
 |
 |  coefs_ : list of shape (n_layers - 1,)
 |      The ith element in the list represents the weight matrix corresponding
 |      to layer i.
 |
 |  intercepts_ : list of shape (n_layers - 1,)
 |      The ith element in the list represents the bias vector corresponding to
 |      layer i + 1.
 |
 |  n_features_in_ : int
 |      Number of features seen during :term:`fit`.
 |
 |      .. versionadded:: 0.24
 |
 |  feature_names_in_ : ndarray of shape (`n_features_in_`,)
 |      Names of features seen during :term:`fit`. Defined only when `X`
 |      has feature names that are all strings.
 |
 |      .. versionadded:: 1.0
 |
 |  n_iter_ : int
 |      The number of iterations the solver has run.
 |
 |  n_layers_ : int
 |      Number of layers.
 |
 |  n_outputs_ : int
 |      Number of outputs.
 |
 |  out_activation_ : str
 |      Name of the output activation function.
 |
 |  See Also
 |  --------
 |  MLPRegressor : Multi-layer Perceptron regressor.
 |  BernoulliRBM : Bernoulli Restricted Boltzmann Machine (RBM).
 |
 |  Notes
 |  -----
 |  MLPClassifier trains iteratively since at each time step
 |  the partial derivatives of the loss function with respect to the model
 |  parameters are computed to update the parameters.
 |
 |  It can also have a regularization term added to the loss function
 |  that shrinks model parameters to prevent overfitting.
 |
 |  This implementation works with data represented as dense numpy arrays or
 |  sparse scipy arrays of floating point values.
 |
 |  References
 |  ----------
 |  Hinton, Geoffrey E. "Connectionist learning procedures."
 |  Artificial intelligence 40.1 (1989): 185-234.
 |
 |  Glorot, Xavier, and Yoshua Bengio.
 |  "Understanding the difficulty of training deep feedforward neural networks."
 |  International Conference on Artificial Intelligence and Statistics. 2010.
 |
 |  :arxiv:`He, Kaiming, et al (2015). "Delving deep into rectifiers:
 |  Surpassing human-level performance on imagenet classification." <1502.01852>`
 |
 |  :arxiv:`Kingma, Diederik, and Jimmy Ba (2014)
 |  "Adam: A method for stochastic optimization." <1412.6980>`
 |
 |  Examples
 |  --------
 |  >>> from sklearn.neural_network import MLPClassifier
 |  >>> from sklearn.datasets import make_classification
 |  >>> from sklearn.model_selection import train_test_split
 |  >>> X, y = make_classification(n_samples=100, random_state=1)
 |  >>> X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y,
 |  ...                                                     random_state=1)
 |  >>> clf = MLPClassifier(random_state=1, max_iter=300).fit(X_train, y_train)
 |  >>> clf.predict_proba(X_test[:1])
 |  array([[0.038..., 0.961...]])
 |  >>> clf.predict(X_test[:5, :])
 |  array([1, 0, 1, 0, 1])
 |  >>> clf.score(X_test, y_test)
 |  0.8...
 |
 |  Method resolution order:
 |      MLPClassifier
 |      sklearn.base.ClassifierMixin
 |      BaseMultilayerPerceptron
 |      sklearn.base.BaseEstimator
 |      sklearn.utils._estimator_html_repr._HTMLDocumentationLinkMixin
 |      sklearn.utils._metadata_requests._MetadataRequester
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, hidden_layer_sizes=(100,), activation='relu', *, solver='adam', alpha=0.0001, batch_size='auto', learning_rate='constant', learning_rate_init=0.001, power_t=0.5, max_iter=200, shuffle=True, random_state=None, tol=0.0001, verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True, early_stopping=False, validation_fraction=0.1, beta_1=0.9, beta_2=0.999, epsilon=1e-08, n_iter_no_change=10, max_fun=15000)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __sklearn_tags__(self)
 |
 |  partial_fit(self, X, y, classes=None)
 |      Update the model with a single iteration over the given data.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          The input data.
 |
 |      y : array-like of shape (n_samples,)
 |          The target values.
 |
 |      classes : array of shape (n_classes,), default=None
 |          Classes across all calls to partial_fit.
 |          Can be obtained via `np.unique(y_all)`, where y_all is the
 |          target vector of the entire dataset.
 |          This argument is required for the first call to partial_fit
 |          and can be omitted in the subsequent calls.
 |          Note that y doesn't need to contain all labels in `classes`.
 |
 |      Returns
 |      -------
 |      self : object
 |          Trained MLP model.
 |
 |  predict(self, X)
 |      Predict using the multi-layer perceptron classifier.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          The input data.
 |
 |      Returns
 |      -------
 |      y : ndarray, shape (n_samples,) or (n_samples, n_classes)
 |          The predicted classes.
 |
 |  predict_log_proba(self, X)
 |      Return the log of probability estimates.
 |
 |      Parameters
 |      ----------
 |      X : ndarray of shape (n_samples, n_features)
 |          The input data.
 |
 |      Returns
 |      -------
 |      log_y_prob : ndarray of shape (n_samples, n_classes)
 |          The predicted log-probability of the sample for each class
 |          in the model, where classes are ordered as they are in
 |          `self.classes_`. Equivalent to `log(predict_proba(X))`.
 |
 |  predict_proba(self, X)
 |      Probability estimates.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          The input data.
 |
 |      Returns
 |      -------
 |      y_prob : ndarray of shape (n_samples, n_classes)
 |          The predicted probability of the sample for each class in the
 |          model, where classes are ordered as they are in `self.classes_`.
 |
 |  set_partial_fit_request(self: sklearn.neural_network._multilayer_perceptron.MLPClassifier, *, classes: Union[bool, NoneType, str] = '$UNCHANGED$') -> sklearn.neural_network._multilayer_perceptron.MLPClassifier from sklearn.utils._metadata_requests.RequestMethod.__get__.<locals>
 |      Request metadata passed to the ``partial_fit`` method.
 |
 |      Note that this method is only relevant if
 |      ``enable_metadata_routing=True`` (see :func:`sklearn.set_config`).
 |      Please see :ref:`User Guide <metadata_routing>` on how the routing
 |      mechanism works.
 |
 |      The options for each parameter are:
 |
 |      - ``True``: metadata is requested, and passed to ``partial_fit`` if provided. The request is ignored if metadata is not provided.
 |
 |      - ``False``: metadata is not requested and the meta-estimator will not pass it to ``partial_fit``.
 |
 |      - ``None``: metadata is not requested, and the meta-estimator will raise an error if the user provides it.
 |
 |      - ``str``: metadata should be passed to the meta-estimator with this given alias instead of the original name.
 |
 |      The default (``sklearn.utils.metadata_routing.UNCHANGED``) retains the
 |      existing request. This allows you to change the request for some
 |      parameters and not others.
 |
 |      .. versionadded:: 1.3
 |
 |      .. note::
 |          This method is only relevant if this estimator is used as a
 |          sub-estimator of a meta-estimator, e.g. used inside a
 |          :class:`~sklearn.pipeline.Pipeline`. Otherwise it has no effect.
 |
 |      Parameters
 |      ----------
 |      classes : str, True, False, or None,                     default=sklearn.utils.metadata_routing.UNCHANGED
 |          Metadata routing for ``classes`` parameter in ``partial_fit``.
 |
 |      Returns
 |      -------
 |      self : object
 |          The updated object.
 |
 |  set_score_request(self: sklearn.neural_network._multilayer_perceptron.MLPClassifier, *, sample_weight: Union[bool, NoneType, str] = '$UNCHANGED$') -> sklearn.neural_network._multilayer_perceptron.MLPClassifier from sklearn.utils._metadata_requests.RequestMethod.__get__.<locals>
 |      Request metadata passed to the ``score`` method.
 |
 |      Note that this method is only relevant if
 |      ``enable_metadata_routing=True`` (see :func:`sklearn.set_config`).
 |      Please see :ref:`User Guide <metadata_routing>` on how the routing
 |      mechanism works.
 |
 |      The options for each parameter are:
 |
 |      - ``True``: metadata is requested, and passed to ``score`` if provided. The request is ignored if metadata is not provided.
 |
 |      - ``False``: metadata is not requested and the meta-estimator will not pass it to ``score``.
 |
 |      - ``None``: metadata is not requested, and the meta-estimator will raise an error if the user provides it.
 |
 |      - ``str``: metadata should be passed to the meta-estimator with this given alias instead of the original name.
 |
 |      The default (``sklearn.utils.metadata_routing.UNCHANGED``) retains the
 |      existing request. This allows you to change the request for some
 |      parameters and not others.
 |
 |      .. versionadded:: 1.3
 |
 |      .. note::
 |          This method is only relevant if this estimator is used as a
 |          sub-estimator of a meta-estimator, e.g. used inside a
 |          :class:`~sklearn.pipeline.Pipeline`. Otherwise it has no effect.
 |
 |      Parameters
 |      ----------
 |      sample_weight : str, True, False, or None,                     default=sklearn.utils.metadata_routing.UNCHANGED
 |          Metadata routing for ``sample_weight`` parameter in ``score``.
 |
 |      Returns
 |      -------
 |      self : object
 |          The updated object.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __abstractmethods__ = frozenset()
 |
 |  __annotations__ = {}
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.ClassifierMixin:
 |
 |  score(self, X, y, sample_weight=None)
 |      Return the mean accuracy on the given test data and labels.
 |
 |      In multi-label classification, this is the subset accuracy
 |      which is a harsh metric since you require for each sample that
 |      each label set be correctly predicted.
 |
 |      Parameters
 |      ----------
 |      X : array-like of shape (n_samples, n_features)
 |          Test samples.
 |
 |      y : array-like of shape (n_samples,) or (n_samples, n_outputs)
 |          True labels for `X`.
 |
 |      sample_weight : array-like of shape (n_samples,), default=None
 |          Sample weights.
 |
 |      Returns
 |      -------
 |      score : float
 |          Mean accuracy of ``self.predict(X)`` w.r.t. `y`.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from sklearn.base.ClassifierMixin:
 |
 |  __dict__

### **Exercício 1c** - Qual o objetivo do parâmetro early stopping?

O parâmetro early_stopping tem como objetivo interromper o treinamento da rede neural antes que ela comece a superajustar os dados de treino (overfitting). Quando ele está ativado (early_stopping=True), o modelo reserva automaticamente uma parte dos dados de treino (10% por padrão) para validação e monitora o desempenho nessa amostra.

Durante o treinamento, se o desempenho (por exemplo, a acurácia ou o erro de validação) parar de melhorar após um certo número de iterações consecutivas, o processo de aprendizado é interrompido automaticamente — mesmo que o número máximo de iterações (max_iter) ainda não tenha sido alcançado. Assim, o early stopping ajuda a evitar que o modelo aprenda ruídos e padrões específicos do conjunto de treino, garantindo melhor generalização nos dados novos

### **Exercício 1d** - Solver foi definido como "sgd", i.e. Stochastic Gradient Descent. O que é o método Gradient Descent?

O Gradient Descent tradicional calcula o gradiente da função de custo usando todo o conjunto de dados de uma vez antes de atualizar os pesos. Isso faz com que cada passo seja mais preciso, porém o processo é mais lento e pesado computacionalmente, especialmente em bases grandes. Ele busca reduzir o erro global de forma estável, mas pode ficar preso em mínimos locais e demora mais para convergir.

Já o Stochastic Gradient Descent (SGD) faz o oposto: ele atualiza os pesos a cada amostra (ou pequeno lote) de dados, em vez de esperar processar todo o conjunto. Isso torna o treinamento muito mais rápido e dinâmico, introduzindo pequenas flutuações no caminho da otimização. Essas variações fazem o modelo escapar de mínimos locais e aprender padrões mais gerais, embora o processo seja menos estável e o erro oscile mais durante o aprendizado.

#**2) Progressão de Diabetes**
Regressão — (1 target numérico, 442 amostras, 10 features)

### **Exercício 2a** - Ajuste um modelo de redes neurais MLP para resolução do problema de progressão de diabetes, determine a quantidade de camadas ocultas e neurônios, bem como a função de ativação da(s) camada(s) oculta(s) (sugestão: teste diferentes valores para encontrar o de melhor desempenho). Configure para utilizar early stopping e defina 1000 iterações máximas.

In [6]:
# Inicialização
import pandas as pd
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np


# Carregar base
X, y = load_diabetes(return_X_y=True)
diabetes = load_diabetes()

# Converter para DataFrame
df = pd.DataFrame(X, columns=diabetes.feature_names)
df["target"] = y

# Ver primeiras linhas
print(df.head())

# Resumo
print(diabetes.DESCR)  # descrição detalhada da base
print(df.info())   # resumo das colunas e tipos
print(df['target'].value_counts())  # quantas amostras em cada classe


# Treino e teste
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=42)

# Padronizar variáveis
scaler = StandardScaler()
X_tr_s = scaler.fit_transform(X_tr)
X_te_s = scaler.transform(X_te)


# Configure os parâmetros corretamente
reg = MLPRegressor(hidden_layer_sizes=(50,), activation="relu",
                   early_stopping=True, solver='adam', max_iter=1000, random_state=42)
reg.fit(X_tr_s, y_tr)

y_pred = reg.predict(X_te_s)
rmse = np.sqrt(mean_squared_error(y_te, y_pred))
print(f"RMSE: {rmse:.3f}  |  R²: {r2_score(y_te, y_pred):.3f}")

        age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142

         s4        s5        s6  target
0 -0.002592  0.019907 -0.017646   151.0
1 -0.039493 -0.068332 -0.092204    75.0
2 -0.002592  0.002861 -0.025930   141.0
3  0.034309  0.022688 -0.009362   206.0
4 -0.002592 -0.031988 -0.046641   135.0
.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

:Number of Instances: 442

:Number of Attributes: First 10 columns are numeric predictive values

:Target: Column 11 is a quantitative measure of disease progression one year after baseline

:Attribute Information:
    - age     age in years
    - sex
    - bmi     body mass index
    - bp      average blood pressure
    - s1      tc, total serum cholesterol
    - s2      ldl, low-density lipoproteins
    - s3      hdl, high-density lipoproteins
    - s4      tch, total cholesterol / HDL
    - s5      ltg, possibly log of serum triglycerides level
    - s6      glu, blood sugar level

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).

Source URL:
https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

For more information see:
Bradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.
(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
 10  target  442 non-null    float64
dtypes: float64(11)
memory usage: 38.1 KB
None
target
200.0    6
72.0     6
178.0    5
71.0     5
90.0     5
        ..
146.0    1
212.0    1
120.0    1
183.0    1
57.0     1
Name: count, Length: 214, dtype: int64
RMSE: 62.062  |  R²: 0.273

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

In [24]:
# Configurações para testar
configs = [
    {"hidden_layer_sizes": (12, 2), "activation": "relu", "solver": "adam"},
    {"hidden_layer_sizes": (30, 4), "activation": "relu", "solver": "adam"},
    {"hidden_layer_sizes": (25, 3), "activation": "tanh", "solver": "adam"},
    {"hidden_layer_sizes": (25, 2), "activation": "tanh", "solver": "adam"},
    {"hidden_layer_sizes": (20, 5), "activation": "relu", "solver": "adam"},
]

# Rodar os testes
results = []
for i, cfg in enumerate(configs, 1):
    model = MLPRegressor(
        hidden_layer_sizes=cfg["hidden_layer_sizes"],
        activation=cfg["activation"],
        solver=cfg["solver"],
        early_stopping=True,
        max_iter=1000,
        random_state=42
    )

    model.fit(X_tr_s, y_tr)
    y_pred = model.predict(X_te_s)

    rmse = float(np.sqrt(mean_squared_error(y_te, y_pred)))
    r2 = float(r2_score(y_te, y_pred))

    results.append({
        "Teste": i,
        "Camadas Ocultas": cfg["hidden_layer_sizes"],
        "Ativação": cfg["activation"],
        "Solver": cfg["solver"],
        "RMSE": round(rmse, 3),
        "R²": round(r2, 3)
    })

    print(f"=== Teste {i} ===")
    print(f"Configuração: {cfg}")
    print(f"RMSE: {rmse:.3f}  |  R²: {r2:.3f}")
    print("-"*50)

# Resumo
df_results = pd.DataFrame(results).sort_values(by="RMSE").reset_index(drop=True)
print("\nResumo dos testes (ordenado por RMSE):")
print(df_results)

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

=== Teste 1 ===
Configuração: {'hidden_layer_sizes': (12, 2), 'activation': 'relu', 'solver': 'adam'}
RMSE: 61.282  |  R²: 0.291
--------------------------------------------------
=== Teste 2 ===
Configuração: {'hidden_layer_sizes': (30, 4), 'activation': 'relu', 'solver': 'adam'}
RMSE: 53.978  |  R²: 0.450
--------------------------------------------------

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

=== Teste 3 ===
Configuração: {'hidden_layer_sizes': (25, 3), 'activation': 'tanh', 'solver': 'adam'}
RMSE: 154.422  |  R²: -3.501
--------------------------------------------------

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

=== Teste 4 ===
Configuração: {'hidden_layer_sizes': (25, 2), 'activation': 'tanh', 'solver': 'adam'}
RMSE: 157.509  |  R²: -3.683
--------------------------------------------------
=== Teste 5 ===
Configuração: {'hidden_layer_sizes': (20, 5), 'activation': 'relu', 'solver': 'adam'}
RMSE: 55.857  |  R²: 0.411
--------------------------------------------------

Resumo dos testes (ordenado por RMSE):
   Teste Camadas Ocultas Ativação Solver     RMSE     R²
0      2         (30, 4)     relu   adam   53.978  0.450
1      5         (20, 5)     relu   adam   55.857  0.411
2      1         (12, 2)     relu   adam   61.282  0.291
3      3         (25, 3)     tanh   adam  154.422 -3.501
4      4         (25, 2)     tanh   adam  157.509 -3.683

Os resultados mostram que as redes neurais com função de ativação ReLU apresentaram desempenho consistentemente superior às configuradas com tanh. O melhor modelo foi o da configuração (30, 4) com ativação ReLU, que obteve o menor erro médio (RMSE ≈ 53,98) e o maior coeficiente de determinação (R² ≈ 0,45), indicando que explicou cerca de 45 % da variabilidade dos dados. As demais arquiteturas com ReLU também tiveram bom desempenho, enquanto as redes com tanh não convergiram adequadamente, resultando em valores de R² negativos e erros elevados (RMSE acima de 150), evidenciando underfitting e dificuldade de aprendizado. Assim, para este conjunto de dados de regressão, a função ReLU demonstrou ser a mais eficaz, combinando estabilidade e melhor capacidade preditiva.

### **Exercício 2b** - De acordo com o tipo de target, qual a função de custo utilizada?


Como o target é contínuo, o MLPRegressor utiliza a função de custo do erro quadrático médio (MSE – Mean Squared Error) para treinar o modelo.

### **Exercício 2c** - Solver foi definido como "adam", i.e. Adaptative Moment Estimation. Como o algoritmo Adam se compara com o Gradient Descent?

O algoritmo Adam (Adaptive Moment Estimation) é uma variação avançada do Gradient Descent que combina as vantagens do momentum e da adaptação da taxa de aprendizado. Enquanto o Gradient Descent tradicional utiliza uma única taxa de aprendizado fixa e se baseia apenas no gradiente atual para ajustar os pesos, o Adam calcula médias móveis dos gradientes e de seus quadrados, permitindo que cada parâmetro tenha sua própria taxa de atualização. Essa abordagem torna o processo de treinamento mais rápido, estável e menos sensível à escolha de hiperparâmetros, sendo especialmente eficaz em problemas complexos e com dados ruidosos, como os que envolvem redes neurais.

### **Exercício 2d** - Que técnicas de tuning de hiperparâmetro poderiam ser utilizadas para encontrar os melhores valores dos hiperparâmetros do modelo?

Para encontrar os melhores valores dos hiperparâmetros do modelo, podem ser aplicadas diferentes técnicas de tuning. Entre as mais utilizadas estão a Grid Search, que realiza uma busca exaustiva testando todas as combinações possíveis dos parâmetros definidos, e a Random Search, que seleciona combinações aleatórias dentro de intervalos pré-estabelecidos, reduzindo o custo computacional. Métodos mais avançados incluem a Bayesian Search, que utiliza princípios de otimização bayesiana para explorar o espaço de busca de forma inteligente, priorizando combinações promissoras, e a Hyperband Search, que combina amostragem aleatória com um mecanismo adaptativo de alocação de recursos, interrompendo precocemente as configurações menos eficazes. Essas técnicas, geralmente associadas à validação cruzada, permitem identificar de forma eficiente os hiperparâmetros que maximizam o desempenho do modelo.